export const theme = {
  ltr: "ltr",
  rtl: "rtl",
  paragraph: "paragraph",
  heading: {
    h1: "heading-h1",
    h2: "heading-h2",
    h3: "heading-h3",
  },
  list: {
    nested: {
      listitem: "nested-listitem",
    },
    ol: "list-ol",
    ul: "list-ul",
    listitem: "listitem",
  },
  text: {
    bold: "text-bold",
    underline: "text-underline",
    italic: "text-italic",
    strikethrough: "text-strikethrough",
    underlineStrikethrough: "text-underline-strikethrough",
  },
  code: "editor-code",
  codeHighlight: {
    atrule: "editor-tokenAttr",
    attr: "editor-tokenAttr",
    boolean: "editor-tokenProperty",
    builtin: "editor-tokenSelector",
    cdata: "editor-tokenComment",
    char: "editor-tokenSelector",
    class: "editor-tokenFunction",
    "class-name": "editor-tokenFunction",
    comment: "editor-tokenComment",
    constant: "editor-tokenProperty",
    deleted: "editor-tokenProperty",
    doctype: "editor-tokenComment",
    entity: "editor-tokenOperator",
    function: "editor-tokenFunction",
    important: "editor-tokenVariable",
    inserted: "editor-tokenSelector",
    keyword: "editor-tokenAttr",
    namespace: "editor-tokenVariable",
    number: "editor-tokenProperty",
    operator: "editor-tokenOperator",
    prolog: "editor-tokenComment",
    property: "editor-tokenProperty",
    punctuation: "editor-tokenPunctuation",
    regex: "editor-tokenVariable",
    selector: "editor-tokenSelector",
    string: "editor-tokenSelector",
    symbol: "editor-tokenProperty",
    tag: "editor-tokenProperty",
    url: "editor-tokenOperator",
    variable: "editor-tokenVariable",
  },
  quote: "quote",
};
